<?php
//SESIOA HASI ETA EZABATU, HORRELA LEHENGO USUARIOAREN VARIABLEAK BORRATZEN DIRA BESTE BAT LOGIN EGITERAKOAN BERRIAK IZATEKO
session_start();
session_destroy();
//LOGOUT EGITERAKOAN LOGINERA BIDALI
header("Location: login.php");
exit;
?>